### ISSUE TITLE
Get basic routes and navigation working

### ISSUE THREAD

**Issue by ejaxon** [cityofasheville/simplicity2#3]
See routes in https://docs.google.com/document/d/1koFuIO7I68NM8oCVMCHgPTEAzD3Y6OFyD5K5qRJbeww/edit#

**Comment by ejaxon** [comment]
I've been thinking a bit about our conversation Friday. I think the conclusion that the routes in SimpliCity should reduce to basically a single generic route is wrong. Routes are an independent concept from the thing that should live at that route. I think we should stick with something like the routes we came up with in the doc referenced above and come up with a way of _registering_ a container that describes a page to that route. In _addition_, we should have something like .../simplicity/snippet?containerid=12345?embedded=true that allows us to reference a specific container. 

Part of the reason is that the route will likely determine the frame within which the container is embedded. In SimpliCitySearch, there might be special navigation stuff, breadcrumbs, etc. We should not define that as part of the container. Also we may want to create alternative entry points - for example, .../internaldashboards might be used by managers to get a more convenient access to their dashboards that does the navigation differently than in the main SimpliCity interface. That way we can tailor the system to different classes of users and use cases without having to write a one-size-fits-all interface frame.

**Comment by carlyleec** [comment]
Added some basic routes: /, /topics, /my-simplicity, and a test topic container
